"""add_package_commerce_system

Revision ID: 9761bc484020
Revises: 49f335edbf16
Create Date: 2026-01-21 18:02:14.661463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9761bc484020'
down_revision: Union[str, None] = '49f335edbf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('total_time_saved', sa.String(), nullable=True),
    sa.Column('tools', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_category'), 'packages', ['category'], unique=False)
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix_packages_is_bundle'), 'packages', ['is_bundle'], unique=False)
    op.create_index(op.f('ix_packages_is_featured'), 'packages', ['is_featured'], unique=False)
    op.create_index(op.f('ix_packages_is_published'), 'packages', ['is_published'], unique=False)
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('payment_provider', sa.Enum('stripe', 'payu', name='paymentprovider'), nullable=False),
    sa.Column('payment_intent_id', sa.String(), nullable=True),
    sa.Column('payment_completed_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_intent_id'), 'orders', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_webhook_processed'), 'orders', ['webhook_processed'], unique=False)
    op.create_table('package_bundle_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bundle_id', sa.Uuid(), nullable=False),
    sa.Column('child_package_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'child_package_id', name='uq_bundle_child_package')
    )
    op.create_index('ix_bundle_items_bundle_child', 'package_bundle_items', ['bundle_id', 'child_package_id'], unique=False)
    op.create_index(op.f('ix_package_bundle_items_bundle_id'), 'package_bundle_items', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_package_bundle_items_child_package_id'), 'package_bundle_items', ['child_package_id'], unique=False)
    op.create_index(op.f('ix_package_bundle_items_id'), 'package_bundle_items', ['id'], unique=False)
    op.create_table('package_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_processes_id'), 'package_processes', ['id'], unique=False)
    op.create_index(op.f('ix_package_processes_package_id'), 'package_processes', ['package_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('package_title', sa.String(), nullable=False),
    sa.Column('package_slug', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_package_id'), 'order_items', ['package_id'], unique=False)
    op.create_table('package_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'package_id', name='uq_user_package_enrollment')
    )
    op.create_index(op.f('ix_package_enrollments_id'), 'package_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_package_enrollments_order_id'), 'package_enrollments', ['order_id'], unique=False)
    op.create_index(op.f('ix_package_enrollments_package_id'), 'package_enrollments', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_enrollments_user_id'), 'package_enrollments', ['user_id'], unique=False)
    op.create_index('ix_package_enrollments_user_package', 'package_enrollments', ['user_id', 'package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_package_enrollments_user_package', table_name='package_enrollments')
    op.drop_index(op.f('ix_package_enrollments_user_id'), table_name='package_enrollments')
    op.drop_index(op.f('ix_package_enrollments_package_id'), table_name='package_enrollments')
    op.drop_index(op.f('ix_package_enrollments_order_id'), table_name='package_enrollments')
    op.drop_index(op.f('ix_package_enrollments_id'), table_name='package_enrollments')
    op.drop_table('package_enrollments')
    op.drop_index(op.f('ix_order_items_package_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_package_processes_package_id'), table_name='package_processes')
    op.drop_index(op.f('ix_package_processes_id'), table_name='package_processes')
    op.drop_table('package_processes')
    op.drop_index(op.f('ix_package_bundle_items_id'), table_name='package_bundle_items')
    op.drop_index(op.f('ix_package_bundle_items_child_package_id'), table_name='package_bundle_items')
    op.drop_index(op.f('ix_package_bundle_items_bundle_id'), table_name='package_bundle_items')
    op.drop_index('ix_bundle_items_bundle_child', table_name='package_bundle_items')
    op.drop_table('package_bundle_items')
    op.drop_index(op.f('ix_orders_webhook_processed'), table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_intent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_index(op.f('ix_packages_is_published'), table_name='packages')
    op.drop_index(op.f('ix_packages_is_featured'), table_name='packages')
    op.drop_index(op.f('ix_packages_is_bundle'), table_name='packages')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_category'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
