"""add_index_points_history_created_at

Revision ID: f2526c1bf680
Revises: 159d7f2a08bd
Create Date: 2026-01-11 22:00:01.691574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2526c1bf680'
down_revision: Union[str, None] = '159d7f2a08bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_points_history_created_at'), 'points_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_history_created_at'), table_name='points_history')
    # ### end Alembic commands ###
